import type { DiffScopeItem } from "../../diff-scope/diffScopes.js";
import type { GitDiffSnapshot } from "../../git-diff/getGitDiffStats.js";
import type { MenuItem } from "../../main-menu/menuItems.js";
import { toDiffContextLines, toMarkdownBlockLines } from "./sharedPrompt.js";

type PromptAgentOutput = {
  readonly content: string;
  readonly verdicts?: {
    readonly verdict: string;
  };
};

export const PR_AGENT_INSTRUCTIONS = [
  "You are a PR agent running inside the review-this CLI after review, lint verification, and optional fixing.",
  "Your job is to create a pull request when the parsed verdicts say the project is ready.",
  "Only proceed when parsed review, lint, and fix verdicts do not report unresolved findings.",
  "Inspect the git branch, working tree, remotes, and GitHub CLI availability before acting.",
  "Do not include `.env`, secrets, credentials, or ignored files in commits.",
  "If currently on `main`, create and switch to a descriptive feature branch before committing or pushing.",
  "If there are uncommitted changes, stage relevant project files and create a concise commit.",
  "Push the branch to origin with upstream tracking when needed.",
  "Create the PR with `gh pr create` when GitHub CLI is installed and authenticated.",
  "Use the required GitHub PR description body from the prompt. Write it to a temporary markdown file and pass it with `gh pr create --body-file <file>`; do not use `--fill` as a substitute for the standardized body.",
  "The GitHub PR description must use exactly these top-level sections: Change Intention, Reviews, What Fixed, Lint and Typecheck Status.",
  "If PR creation is blocked, report the blocker and the exact commands the user can run next; do not fake a PR URL.",
  "Return Markdown only.",
  "Use exactly these top-level sections for your final agent response: PR Summary, Git State, Result.",
  "Under Result, include `PR: <url>` when created, otherwise `PR: not created`.",
].join("\n");

export function toPrPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: PromptAgentOutput | undefined,
  fix: PromptAgentOutput | undefined,
  lint: PromptAgentOutput,
): string {
  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    "PR workflow:",
    "1. Confirm parsed verdicts permit a PR: lint passed with no unresolved review findings, or a later fix verdict is fixed after review or lint failures.",
    "2. Inspect `git status --short --branch`, `git remote -v`, and GitHub CLI auth state.",
    "3. Create/switch to a feature branch if needed.",
    "4. Commit relevant changes if needed.",
    "5. Build the PR description from the required template below.",
    "6. Write the PR description to a temporary markdown file and create the PR with `gh pr create --body-file <file>` if possible.",
    "",
    "PR description rules:",
    "- Use concise summaries first, then collapsible details for original agent outputs.",
    "- Preserve the original review, fix, and lint outputs inside their matching details blocks.",
    "- Do not paste the original git diff into the PR description.",
    "- If a section has no source output, say so plainly instead of inventing content.",
    "",
    "Parsed verdicts:",
    `- Review: ${review?.verdicts?.verdict ?? "missing"}`,
    `- Fix: ${fix?.verdicts?.verdict ?? (fix === undefined ? "not run" : "missing")}`,
    `- Lint: ${lint.verdicts?.verdict ?? "missing"}`,
    "",
    ...toMarkdownBlockLines(
      "Review output:",
      "markdown",
      review?.content,
      "(no review output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Fix output:",
      "markdown",
      fix?.content,
      "(no fix output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Lint output:",
      "markdown",
      lint.content,
      "(empty lint output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Original git diff:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    ...toPrBodyTemplateLines(),
    "",
    "Required Markdown structure for your final agent response:",
    "## PR Summary",
    "- <what was prepared>",
    "",
    "## Git State",
    "- <branch, commit, remote, push status>",
    "",
    "## Result",
    "PR: <url|not created>",
  ].join("\n");
}

function toPrBodyTemplateLines(): string[] {
  return [
    "Required GitHub PR description body:",
    "````markdown",
    "## Change Intention",
    "<Concise summary of the intended change, based on the review output and diff context.>",
    "",
    "## Reviews",
    "<Concise summary of the original review outcome.>",
    "",
    "<details>",
    "<summary>Original review output</summary>",
    "",
    "```markdown",
    "<Paste the full original review output here.>",
    "```",
    "",
    "</details>",
    "",
    "## What Fixed",
    "<Concise summary of what the fix agent changed, or say that no fix step was required.>",
    "",
    "<details>",
    "<summary>Fix agent output</summary>",
    "",
    "```markdown",
    "<Paste the full fix agent output here, or `(no fix output)`.>",
    "```",
    "",
    "</details>",
    "",
    "## Lint and Typecheck Status",
    "- Typecheck: <passed|failed|skipped> - <command or reason from lint output>",
    "- Lint: <passed|failed|skipped> - <command or reason from lint output>",
    "- Test: <passed|failed|skipped> - <command or reason from lint output, if present>",
    "- Build: <passed|failed|skipped> - <command or reason from lint output, if present>",
    "",
    "<details>",
    "<summary>Verification output</summary>",
    "",
    "```markdown",
    "<Paste the full lint output here.>",
    "```",
    "",
    "</details>",
    "````",
  ];
}
